"""
Environment Configuration Dialog

Tkinter GUI for creating / editing the .env file.
Called by start.bat when .env is missing, or directly: python setup_env.py
"""

import os
import sys
import tkinter as tk
from tkinter import ttk, messagebox

ENV_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")

# Field definitions: (env_key, label, required, placeholder, is_password)
FIELDS = [
    ("DEEPSEEK_API_KEY",      "DeepSeek API Key",       True,  "sk-...",                           True),
    ("DEEPSEEK_BASE_URL",     "DeepSeek Base URL",      False, "https://api.deepseek.com",         False),
    ("PADDLEOCR_REMOTE_URL",  "PaddleOCR API URL",      False, "https://your-paddleocr-endpoint",  False),
    ("PADDLEOCR_REMOTE_TOKEN","PaddleOCR API Token",     False, "",                                 True),
    ("QWEN_API_KEY",          "Qwen Vision API Key",    False, "sk-...",                           True),
]


def load_existing():
    """Load existing .env values into a dict."""
    values = {}
    if os.path.exists(ENV_PATH):
        with open(ENV_PATH, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    k, v = line.split("=", 1)
                    values[k.strip()] = v.strip()
    return values


def save_env(values):
    """Write values to .env file."""
    lines = [
        "# Deep Reading Agent - Environment Configuration",
        "# Auto-generated by setup_env.py",
        "",
    ]
    for key, label, required, placeholder, _ in FIELDS:
        val = values.get(key, "").strip()
        if val:
            lines.append(f"{key}={val}")
        elif not required:
            lines.append(f"# {key}=")
    lines.append("")
    with open(ENV_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def run_dialog():
    existing = load_existing()

    root = tk.Tk()
    root.title("Deep Reading Agent - Environment Setup")
    root.resizable(False, False)

    # Center window
    w, h = 560, 420
    sx = root.winfo_screenwidth() // 2 - w // 2
    sy = root.winfo_screenheight() // 2 - h // 2
    root.geometry(f"{w}x{h}+{sx}+{sy}")

    frame = ttk.Frame(root, padding=20)
    frame.pack(fill="both", expand=True)

    ttk.Label(frame, text="Deep Reading Agent", font=("", 14, "bold")).grid(
        row=0, column=0, columnspan=2, pady=(0, 5), sticky="w"
    )
    ttk.Label(frame, text="Configure API keys. Only DeepSeek is required.").grid(
        row=1, column=0, columnspan=2, pady=(0, 15), sticky="w"
    )

    entries = {}
    for i, (key, label, required, placeholder, is_pw) in enumerate(FIELDS):
        row = i + 2
        tag = " *" if required else ""
        ttk.Label(frame, text=f"{label}{tag}:").grid(row=row, column=0, sticky="e", padx=(0, 8), pady=4)

        var = tk.StringVar(value=existing.get(key, ""))
        entry = ttk.Entry(frame, textvariable=var, width=48, show="*" if is_pw else "")
        entry.grid(row=row, column=1, sticky="w", pady=4)

        # Show placeholder as grey text when empty
        if not var.get() and placeholder and not is_pw:
            entry.insert(0, placeholder)
            entry.config(foreground="grey")

            def on_focus_in(e, ent=entry, ph=placeholder):
                if ent.get() == ph:
                    ent.delete(0, "end")
                    ent.config(foreground="black")

            def on_focus_out(e, ent=entry, ph=placeholder, v=var):
                if not ent.get():
                    ent.insert(0, ph)
                    ent.config(foreground="grey")
                    v.set("")

            entry.bind("<FocusIn>", on_focus_in)
            entry.bind("<FocusOut>", on_focus_out)

        entries[key] = (var, placeholder)

    # Toggle password visibility
    show_var = tk.BooleanVar(value=False)

    def toggle_show():
        for key, label, req, ph, is_pw in FIELDS:
            if is_pw:
                # Find the entry widget
                for child in frame.winfo_children():
                    if isinstance(child, ttk.Entry):
                        info = child.grid_info()
                        field_row = int(info.get("row", -1))
                        idx = field_row - 2
                        if 0 <= idx < len(FIELDS) and FIELDS[idx][0] == key:
                            child.config(show="" if show_var.get() else "*")

    row_after = len(FIELDS) + 2
    ttk.Checkbutton(frame, text="Show keys", variable=show_var, command=toggle_show).grid(
        row=row_after, column=1, sticky="w", pady=(5, 0)
    )

    # Status label
    status_var = tk.StringVar(value="")
    ttk.Label(frame, textvariable=status_var, foreground="green").grid(
        row=row_after + 1, column=0, columnspan=2, pady=(5, 0), sticky="w"
    )

    result = {"saved": False}

    def on_save():
        values = {}
        for key, (var, placeholder) in entries.items():
            val = var.get().strip()
            # Don't save placeholder text as actual value
            if val == placeholder:
                val = ""
            values[key] = val

        # Validate required
        if not values.get("DEEPSEEK_API_KEY"):
            messagebox.showwarning("Missing Required Field", "DeepSeek API Key is required.\n\nGet one at: https://platform.deepseek.com/")
            return

        save_env(values)
        result["saved"] = True
        status_var.set(f"Saved to {ENV_PATH}")
        root.after(800, root.destroy)

    def on_skip():
        if not os.path.exists(ENV_PATH):
            # Create minimal .env so app can at least start
            save_env({})
        result["saved"] = True
        root.destroy()

    btn_frame = ttk.Frame(frame)
    btn_frame.grid(row=row_after + 2, column=0, columnspan=2, pady=(15, 0))

    ttk.Button(btn_frame, text="Save & Start", command=on_save).pack(side="left", padx=5)
    ttk.Button(btn_frame, text="Skip (start without saving)", command=on_skip).pack(side="left", padx=5)
    ttk.Button(btn_frame, text="Cancel", command=lambda: sys.exit(1)).pack(side="left", padx=5)

    root.mainloop()
    return result["saved"]


if __name__ == "__main__":
    success = run_dialog()
    sys.exit(0 if success else 1)
