class StataGenerator:
    def generate_code(self, methodology_text, variables):
        """
        Generates Stata code based on methodology keywords and extracted variables.
        """
        code = []
        code.append("* Stata Code Generated by Academic PDF Analyzer")
        code.append("clear all")
        code.append("set more off")
        code.append("")
        
        # Load Data
        code.append("* 1. Load Data")
        code.append('use "your_dataset.dta", clear')
        code.append("")
        
        # Define Variables
        y = variables.get('dependent', ['y'])[0] if variables.get('dependent') else 'y'
        x = variables.get('independent', ['x'])[0] if variables.get('independent') else 'x'
        controls = " ".join(variables.get('controls', ['control1', 'control2']))
        
        code.append(f"* Dependent Variable: {y}")
        code.append(f"* Independent Variable: {x}")
        code.append(f"global controls {controls}")
        code.append("")
        
        # Determine Model
        method_lower = methodology_text.lower()
        
        code.append("* 2. Main Regression Analysis")
        
        if "panel" in method_lower or "fixed effect" in method_lower or "面板" in method_lower or "固定效应" in method_lower:
            code.append("* Panel Data Fixed Effects Model")
            code.append("xtset id year")
            code.append(f"reghdfe {y} {x} $controls, absorb(id year) cluster(id)")
        elif "instrument" in method_lower or "iv" in method_lower or "2sls" in method_lower or "工具变量" in method_lower:
            code.append("* Instrumental Variable Estimation (2SLS)")
            code.append(f"ivreg2 {y} ($controls) ({x} = iv), cluster(id)")
        elif "difference in difference" in method_lower or "did" in method_lower or "双重差分" in method_lower or "倍差法" in method_lower:
            code.append("* Difference-in-Differences Model")
            code.append(f"reghdfe {y} c.post#c.treat $controls, absorb(id year) cluster(id)")
        elif "discontinuity" in method_lower or "rdd" in method_lower or "断点回归" in method_lower:
            code.append("* Regression Discontinuity Design")
            code.append(f"rdplot {y} running_var")
        else:
            code.append("* OLS Regression (Default)")
            code.append(f"reg {y} {x} $controls, robust")
            
        code.append("")
        code.append("* 3. Export Results")
        code.append(f"outreg2 using results.doc, replace word")
        
        return "\n".join(code)
